name: KNK

on:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Setup Dependencies
        run: |
          nohup --version
          sudo apt-get update
          sudo apt-get install libpcap-dev 
          #sudo apt-get install nohup
      - name: Cache Go
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Setting up ProjectDiscovery tools
        env:
          GO111MODULE: on
        run: |
          go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install -v github.com/projectdiscovery/katana/cmd/katana@latest
          go install -v github.com/tomnomnom/anew@latest
          go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
          #go install -v github.com/projectdiscovery/dnsx/cmd/dnsx@latest
          #go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
          #go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
          #go install -v github.com/projectdiscovery/mapcidr/cmd/mapcidr@latest
        shell: bash

      - name: Running substr3 and httpx for HTTP webservers probbing
        run: |
          subfinder -silent -dL input/domains.txt -config config/subfinder-config.yaml | anew output/passive_subdomains.txt | httpx -silent | anew output/active_urls.txt
        shell: bash


      - name: KAK listen
        run: |
          wget https://github.com/chaitin/xray/releases/download/1.9.3/xray_linux_amd64.zip
          unzip xray_linux_amd64.zip
          mv xray_linux_amd64 xray
          #set +e ;for i in $(cat active_urls.txt ); do ./xray webscan --basic-crawler $i --html-output output/`date +%Y%m%d%H%M%S`.html;done
          #cat output/*.html >> output/xray.html
          #set +e ;for i in $(cat output/active_urls.txt ); do ./xray webscan --plugins xss,sqldet --basic-crawler $i --json-output `date +%Y%m%d%H%M%S`.json;done
          #cat *.json >> xray.json
          #set +e ;for i in $(cat output/active_urls.txt ); do ./xray webscan --plugins xss,sqldet --basic-crawler $i --json-output xray.html;done
          ./xray
          /usr/bin/nohup ./xray webscan --plugins xss,sqldet --listen 127.0.0.1:7777  --html-output xray.html &
        shell: bash

      - name: KAK scanns
        run: |
          set +e ;for i in $(cat output/active_urls.txt ); do katana -u $i -aff -H -jc -d 7 -proxy http://127.0.0.1:7777; done
        shell: bash

      - name: Sorting the output results
        run: |
          find output -type f -exec sort {} -o {} \;
        shell: bash

      - name: Create local changes
        run: |
          git add output/active_urls.txt
          git add output/xray.html
      - name: Commit results to Github
        run: |
          git config --local user.email "jinbao1986@qq.com"
          git config --global user.name "TNT"
          git commit -m "InCloud Report" -a --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
