name: YQY

on:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Dependencies
        run: |
          nohup --version
          python3 -V
          sudo apt-get update
          sudo apt-get install libpcap-dev 
          git clone https://github.com/zhujieta0/userefuzz
          pwd
          ls -al userefuzz
          #pip3 install userefuzz
          sudo python3 userefuzz/setup.py install
          python3 userefuzz/userefuzz/userefuzz.py --help
          #cat active_urls.txt
          python3 userefuzz/userefuzz/userefuzz.py -l active_urls.txt
