name: YQY

on:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Dependencies
        run: |
          nohup --version
          python3 -V
          sudo apt-get update
          sudo apt-get install libpcap-dev 
          git clone https://github.com/root-tanishq/userefuzz
          pwd
          ll -al userefuzz
          python3 pip install userefuzz
          python3 userefuzz/setup.py install
          python3 userefuzz/userefuzz/userefuzz.py --help
